include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Ignore deprecation warnings for assignment purposes
    deprecated_member_use: ignore
    # Ignore style preferences that don't affect functionality  
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_final_fields: ignore
    use_build_context_synchronously: ignore