// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB08zuwDzlqXuxPF0yagWeVpYGM4iKq-Wk',
    appId: '1:872832157007:web:60501ae96033ba6335b13a',
    messagingSenderId: '872832157007',
    projectId: 'bookswap-d71af',
    authDomain: 'bookswap-d71af.firebaseapp.com',
    storageBucket: 'bookswap-d71af.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB08zuwDzlqXuxPF0yagWeVpYGM4iKq-Wk',
    appId: '1:872832157007:android:60501ae96033ba6335b13a',
    messagingSenderId: '872832157007',
    projectId: 'bookswap-d71af',
    storageBucket: 'bookswap-d71af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB08zuwDzlqXuxPF0yagWeVpYGM4iKq-Wk',
    appId: '1:872832157007:ios:60501ae96033ba6335b13a',
    messagingSenderId: '872832157007',
    projectId: 'bookswap-d71af',
    storageBucket: 'bookswap-d71af.firebasestorage.app',
    iosClientId: '872832157007-203s3tkn5ucallbqt0hjnl6e51gb6f5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB08zuwDzlqXuxPF0yagWeVpYGM4iKq-Wk',
    appId: '1:872832157007:ios:60501ae96033ba6335b13a',
    messagingSenderId: '872832157007',
    projectId: 'bookswap-d71af',
    storageBucket: 'bookswap-d71af.firebasestorage.app',
    iosClientId: '872832157007-203s3tkn5ucallbqt0hjnl6e51gb6f5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB08zuwDzlqXuxPF0yagWeVpYGM4iKq-Wk',
    appId: '1:872832157007:web:60501ae96033ba6335b13a',
    messagingSenderId: '872832157007',
    projectId: 'bookswap-d71af',
    authDomain: 'bookswap-d71af.firebaseapp.com',
    storageBucket: 'bookswap-d71af.firebasestorage.app',
  );
}